using System.Reflection.Emit;
using Authentication_Service.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

public class RoleConfiguration : IEntityTypeConfiguration<Role>
{
    public void Configure(EntityTypeBuilder<Role> builder)
    {
        builder.HasKey(r => r.RoleID);
        builder.Property(r => r.Name).IsRequired().HasMaxLength(255);
        builder.Property(r => r.Description).IsRequired();

        //set userId to be autogenerated
        builder.Property(u => u.RoleID)
           .ValueGeneratedOnAdd();
    }

}
