using Authentication_Service.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.HasKey(u => u.UserId);
        builder.Property(u => u.FirstName).IsRequired().HasMaxLength(255);
        builder.Property(u => u.LastName).IsRequired().HasMaxLength(255);
        builder.Property(u => u.Age).IsRequired();
        builder.Property(u => u.Email).IsRequired().HasMaxLength(255);
        builder.Property(u => u.Password).IsRequired();
        builder.Property(u => u.PasswordConfirm).IsRequired();
        builder.Property(u => u.ResetPasswordToken);
        builder.Property(u => u.ResetPasswordTokenExpiry);

        //set userId to be autogenerated
        builder.Property(u => u.UserId)
           .ValueGeneratedOnAdd()
           .HasDefaultValueSql("10000");
        //set time stamp data type 
        builder.Property(u => u.ResetPasswordTokenExpiry).HasColumnType("timestamp with time zone");

        //make email to be unique accross the entire app
        builder.HasIndex(u => u.Email).IsUnique();
    }

}
